### ISSUE TITLE
The value name `style-names` is not mentioned in `READE.md`

### ISSUE THREAD

**Issue by JounQin** [jaywcjlove/stylus-px2rem#2]
This value name is very important but it is  not mentioned in `READE.md` which makes me confused when I change the value `html-font-size`.

P.S.: I'm trying to use [lib-flexible](https://github.com/amfe/lib-flexible) which default base rem is `75px`.

**Comment by jaywcjlove** [comment]
update  + stylus-px2rem@1.0.9
